# Generated by Django 5.0.7 on 2024-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_notes', '0002_alter_content_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
