# Generated by Django 5.0.7 on 2024-07-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='timing',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
