# Generated by Django 5.0.7 on 2024-07-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicure', '0002_service_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='timing',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
